// Generated by CoffeeScript 1.8.0
var docgen, each;

each = require('each');

docgen = require('docgen');

docgen({
  source: ["" + __dirname + "/index.coffee", "" + __dirname + "/client.coffee", "" + __dirname + "/connection.coffee", "" + __dirname + "/table.coffee", "" + __dirname + "/row.coffee", "" + __dirname + "/scanner.coffee"],
  destination: ["" + __dirname + "/../doc/", process.env.HBASE_DOC],
  jekyll: {
    language: 'en',
    layout: 'page',
    comments: 'false',
    sharing: 'false',
    footer: 'false',
    navigation: 'hbase',
    github: 'https://github.com/wdavidw/node-hbase'
  }
}, function(err, hum) {
  return console.log('Documentation generated');
});
